
let products = {
    data:[{
        id: "product1",
        productName: "Ruby Necklace",
        category: "Ruby",
        price: "100",
        quality: "S62",
        Image: "/product_images/ruby_necklace.png",
    },
    {
        id: "product2",
        productName: "Ruby Necklace 2",
        category: "Ruby",
        price: "100",
        quality: "AL8",
        Image: "/product_images/ruby_necklace2.png",
    },
    {
        id: "product3",
        productName: "Ruby Necklace 3",
        category: "Ruby",
        price: "100",
        quality: "S2",
        Image: "/product_images/ruby_necklace3.png",
    },
    {
        id: "product4",
        productName: "Ruby Necklace 4",
        category: "Ruby",
        price: "100",
        quality: "VS2",
        Image: "/product_images/ruby_necklace4.png",
    },
    {
        id: "product5",
        productName: "Ruby Necklace 5",
        category: "Ruby",
        price: "100",
        quality: "SW9",
        Image: "/product_images/ruby_necklace5.png",
    },
    {
        id: "product6",
        productName: "Ruby ring 1",
        category: "Ruby",
        price: "100",
        quality: "TT1",
        Image: "/product_images/ruby_fingerring1.png",
    },
    {
        id: "product7",
        productName: "Ruby ring 2",
        category: "Ruby",
        price: "100",
        quality: "TT8",
        Image: "/product_images/ruby_finger-ring.png",
    },
    {
        id: "product8",
        productName: "Ruby ring 3",
        category: "Ruby",
        price: "100",
        quality: "TT7",
        Image: "/product_images/ruby_fingerring2.png",
    },
    {
        id: "product9",
        productName: "diamond ring 1",
        category: "Diamond",
        price: "200",
        quality: "L62",
        Image: "/product_images/diamond_fingerring1.png",
    },
    {
        id: "product10",
        productName: "diamond necklace",
        category: "Diamond",
        price: "200",
        quality: "M32",
        Image: "/product_images/diamond_necklace.png",
    },
    {
        id: "product11",
        productName: "diamond necklace 1",
        category: "Diamond",
        price: "200",
        quality: "SX2",
        Image: "/product_images/diamnod_necklace.png",
    },
    {
        id: "product12",
        productName: "Sapphire necklace 1",
        category: "Sapphire",
        price: "200",
        quality: "SS1",
        Image: "/product_images/sapphire_necklace.png",
    },
    {
        id: "product13",
        productName: "Sapphire necklace 2",
        category: "Sapphire",
        price: "200",
        quality: "SVS2",
        Image: "/product_images/sapphire_necklace1.png",
    },
    {
        id: "product14",
        productName: "diamond ring",
        category: "Diamond",
        price: "200",
        quality: "V5",
        Image: "/product_images/diamond_Fingerring.png",
    },
    {
        id: "product15",
        productName: "Diamond Stone",
        category: "Diamond",
        price: "4000",
        quality: "VS5",
        Image: "/images/diamond.png",
    },
    {
        id: "product16",
        productName: "Sapphire Stone",
        category: "Diamond",
        price: "4000",
        quality: "VF5",
        Image: "images/sapphire1.png",
    },
    {
        id: "product17",
        productName: "EMERALD Stone",
        category: "Diamond",
        price: "4000",
        quality: "V5",
        Image: "images/emerald.png",
    },
    {
        id: "product18",
        productName: "Ruby Stone",
        category: "Ruby",
        price: "4000",
        quality: "V5",
        Image: "images/ruby-stone-2771.png",
    },
    {
        id: "product19",
        productName: "RUBY NECKLACE",
        category: "Ruby",
        price: "1500",
        quality: "V5",
        Image: "images/necklace.png",
    },
    {
        id: "product20",
        productName: "SAPPHIRE EAR-RINGS",
        category: "Sapphire",
        price: "2000",
        quality: "VK5",
        Image: "images/earRing.png",
    },
    {
        id: "product21",
        productName: "GREEN-DIAMOND BRACELET",
        category: "Diamond",
        price: "1200",
        quality: "VV5",
        Image: "images/barcelet.png",
    },
    {
        id: "product22",
        productName: "DIAMOND NOSERING",
        category: "Diamond",
        price: "1900",
        quality: "VS5",
        Image: "images/noseRing.png",
    },
],
};
